version: "3.9"

services:
  frontend:
    image: vnodocker/petmanage-front
    container_name: petmanage_front
    ports:
      - "4000:80"   # host:container
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: vnodocker/petmanage-back
    container_name: petmanage_back
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
